[package]
name = "lrgex_compress"
version = "1.5.0"
edition = "2021"
description = "LRGEX Compress — standalone fast .tar.zst compressor/extractor"

[[bin]]
name = "lrgex-compress"
path = "src/main.rs"

[[bin]]
name = "sign"
path = "src/sign.rs"

[dependencies]
tar = "0.4"
zstd = { version = "0.13", features = ["zstdmt"] }
rayon = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
slint = { version = "1.10", default-features = false, features = ["std", "compat-1-2", "backend-winit", "renderer-software"] }
rfd = "0.15"
ureq = { version = "2", features = ["json"] }
hex = "0.4"
rand = "0.8"
ed25519-dalek = "2"
backtrace = "0.3"
sha2 = "0.10"
windows-sys = { version = "0.59", features = [
    "Win32_Foundation",
    "Win32_System_Threading",
    "Win32_Security",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_Kernel",
    "Win32_System_LibraryLoader",
    "Win32_Storage_FileSystem",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
] }
unrar = "0.5"
zip = { version = "8", default-features = false, features = ["deflate-flate2-zlib-ng", "deflate64", "bzip2", "zstd", "lzma", "time", "aes-crypto"] }

[build-dependencies]
winres = "0.1"

[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true
debug = "line-tables-only"

[patch.crates-io]
unrar = { path = "vendor/unrar" }
libz-ng-sys = { path = "vendor/libz-ng-sys" }
